### model
model_name_or_path: apple/DiffuCoder-7B-cpGRPO

### method
stage: sft                 # ← keep!
do_train: true

# precision / memory helpers
gradient_checkpointing: true

# ===== freeze tuning =====
finetuning_type: freeze
freeze_trainable_layers: 8   # +8 → last 8 layers are trainable
freeze_trainable_modules: all
freeze_extra_modules: lm_head   # still update the output head



### dataset
dataset: omnisvg_generation_less_than_1024_tokens
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/debug
logging_steps: 10
max_samples: 200
save_steps: 500
plot_loss: true
overwrite_output_dir: true
trust_remote_code: true
### train
optim: paged_adamw_32bit              # bitsandbytes paged optimiser
flash_attn: fa2                       # efficient attention
per_device_train_batch_size: 4
gradient_accumulation_steps: 32
learning_rate: 5.0e-4
num_train_epochs: 300
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps 
eval_steps: 250

### wandb
report_to: wandb
run_name: debug-diffusion
# wandb_project: svg-generation
# wandb_watch: gradients  # Track gradients
# wandb_log_model: true   # Save model artifacts
