### model
model_name_or_path: ./DiffuCoder-local

### method
stage: sft                 # ← keep!
do_train: true

# precision / memory helpers
gradient_checkpointing: true

# ===== LoRA tuning =====
finetuning_type: lora
lora_target: all
lora_rank: 64
lora_alpha: 16
lora_dropout: 0.1



### dataset
dataset: omnisvg_generation_less_than_256_tokens_train_only
template: qwen
cutoff_len: 350
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/diffucoder-svg-lora-less-than-256-lora-rank=64
logging_steps: 10
# max_samples: 100
save_steps: 500
plot_loss: true
overwrite_output_dir: true
trust_remote_code: true
### train
optim: paged_adamw_32bit              # bitsandbytes paged optimiser
flash_attn: fa2                       # efficient attention
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 20
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps 
# eval_steps: 250

### wandb
report_to: wandb
run_name: lora-diffusion-svg-generation-less-than-256-tokens
# wandb_project: debug-diffucoder
# wandb_watch: gradients  # Track gradients
# wandb_log_model: true   # Save model artifacts
